### ISSUE TITLE
Create ERD diagram

### ISSUE THREAD

**Issue by lukieh2014** [GabrielNsiah/Plant-Health-Monitoring-at-LNMH#11]
# Description: 
This task involves creating an Entity Relationship Diagram in 3NF to effectively model the database structure and tables.

# Outcome: 
A complete ERD, with tables, columns, data types and relationships all outlined specifically.

# Design: 
See the final ERD below:
![Image](https://github.com/user-attachments/assets/10188050-f5e5-4df8-948f-d6b4e4f8873f)

# User Story: 
As a developer and architect, I would like to plan out my database structure in advance using an ERD, so that when it comes to creating the database it is easy to follow and ensures it is in 3NF.

**Comment by GabrielNsiah** [comment]
Good Work! 
I am taking off points for the loop
